development:
  adapter: postgresql
  encoding: unicode
  database: sf_demo_development
  pool: 5
  username: labonwheels
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sf_demo_app_pro
  pool: 5
  username: labonwheels
  password:
