development:
  adapter: postgresql
  encoding: unicode
  database: sf_demo_app_dev
  pool: 5
  username: sf_demo
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sf_demo_app_pro
  pool: 5
  username: sf_demo
  password:
