development:
  adapter: postgresql
  encoding: unicode
  database: da3fltfu7jffti
  username: yuikvxirgsajjc
  password: 9efb84bb2938958b746a79d8c2821ae3eb47938c9426acf97658b5f304cf8c77
  host: ec2-174-129-227-80.compute-1.amazonaws.com
